# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: one-api:gpt-41
clients:
- type: openai-compatible
  name: one-api
  api_base: http://one-api.local/v1
  api_key: sk-ptkx18Jhorhk7bS89816B737B274476484Da2741B4D48e67
  models:
  - name: gpt-41
  - name: claude-3-7-sonnet-latest
  - name: DeepSeek-V3-0324
  - name: o4-mini
